ACTION_DATE=3
FISCAL_YEAR=5
TOTAL_OBLIGATION=8
AWARDING_AGENCY_ID=17
FUNDING_AGENCY_ID=18
cat transaction.csv |
	cut -d"," -f ${ACTION_DATE},${FISCAL_YEAR},${TOTAL_OBLIGATION},${AWARDING_AGENCY_ID},${FUNDING_AGENCY_ID} |
	cat > cut_transaction.csv
